# Generated by Django 5.1.1 on 2025-03-18 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date the task was created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(help_text='The end date of the task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(help_text='The start date of the task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(help_text='A brief description of the task', max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', help_text='The priority level of the task', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(help_text='The title of the task', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Team', 'Team')], default='Individual', help_text='The type of task (Individual or Team)', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date the task was last updated'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='assigned_by',
            field=models.ForeignKey(help_text='The user who assigned the task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date the task was assigned'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='The date the task was completed', null=True),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', help_text='The current status of the task', max_length=200),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='task',
            field=models.ForeignKey(help_text='The task being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='task.task'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='Unique ID for the employee', max_length=50, unique=True)),
                ('joining_date', models.DateField(blank=True, help_text='The date the employee joined', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='task.employee'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='employee',
            field=models.ForeignKey(help_text='The employee to whom the task is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='task.employee'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, help_text='The department managed by this user', max_length=100)),
                ('title', models.CharField(default='Manager', help_text='The managerial title (e.g., Team Lead, Manager)', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='The manager overseeing this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='task.manager'),
        ),
    ]
